### ISSUE TITLE
Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication

### ISSUE THREAD

**Issue by bozhiqian** [microsoftgraph/xamarin-csharp-connect-sample#22]
I debug it in VS2017 emulator for Android, when I click the "Connect" button, exception thrown.

```
02-16 16:28:33.543 E/mono    ( 8897): Unhandled Exception:
02-16 16:28:33.543 E/mono    ( 8897): Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication
02-16 16:28:33.543 E/mono    ( 8897):   at (wrapper dynamic-method) System.Object:929ef8ec-110b-4c08-8b50-fdd5fb865be8 (intptr,intptr)
02-16 16:28:33.543 E/mono    ( 8897):   ErrorCode: chrome_not_installed
02-16 16:28:33.543 E/mono-rt ( 8897): [ERROR] FATAL UNHANDLED EXCEPTION: Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication
02-16 16:28:33.543 E/mono-rt ( 8897):   at (wrapper dynamic-method) System.Object:929ef8ec-110b-4c08-8b50-fdd5fb865be8 (intptr,intptr)
02-16 16:28:33.543 E/mono-rt ( 8897):   ErrorCode: chrome_not_installed
```

And then I installed Google Chrome on emulator, but when I run Chrome, I got "Unfortunately, Chrome has stopped" in emulator. I searched google but none of troubleshooting can resolve Chrome issue.

The emulator comes with default browser, why Microsoft.Identity.Client need to use Chrome only?

**Comment by limefrogyank** [comment]
I stopped using the Visual Studio Android Emulator and started using the newer Android Device Manager emulators.  There are some that will use Hyper-V just like the VS version did.  Also, these newer ones have Chrome pre-installed, plus they work with the Play Store.  This fixed the same issue for me.

**Comment by jasonjoh** [comment]
We're archiving this sample and redirecting folks to https://github.com/microsoftgraph/msgraph-training-xamarin (or the corresponding walkthrough at https://docs.microsoft.com/graph/tutorials/xamarin.
