### ISSUE TITLE
UWP not redirecting to login

### ISSUE THREAD

**Issue by stownend** [microsoftgraph/xamarin-csharp-connect-sample#24]
I have got this working on Android. However on UWP I tap the connect button but then nothing happens other than an immediate null reference exception on this line...

var currentUserObject = await graphClient.Me.Request().GetAsync();

On Android I see that it opens the browser and redirects to the login URL. However, no browser opens in UWP. I am running on WIndows 10 (build 1803) and using Visual Studio 2017.

I did have to update all of the nuget packages because of other errors related to EmbeddedResouces not being supported etc.

Any ideas?

**Comment by jasonjoh** [comment]
We're archiving this sample and redirecting folks to https://github.com/microsoftgraph/msgraph-training-xamarin (or the corresponding walkthrough at https://docs.microsoft.com/graph/tutorials/xamarin.
