### ISSUE TITLE
Cant debug on Android Emulator

### ISSUE THREAD

**Issue by coatsy** [microsoftgraph/xamarin-csharp-connect-sample#3]
Building and running with the VS Android Emulator (5" KitKat (4.4) XXHDPI Phone (Android 4.4 - API 19))

```
05-25 09:08:01.465 D/Mono    ( 1463): AOT module 'mscorlib.dll.so' not found: dlopen failed: library "/data/app-lib/XamarinConnect.Droid-1/libaot-mscorlib.dll.so" not found
05-25 09:08:01.465 D/Mono    ( 1463): AOT module '/Users/builder/data/lanes/2923/39a97ef2/source/monodroid/builds/install/mono-x86/lib/mono/aot-cache/x86/mscorlib.dll.so' not found: dlopen failed: library "/data/app-lib/XamarinConnect.Droid-1/libaot-mscorlib.dll.so" not found
```

App launches, (not connected to debugger) and then crashes after login

**Comment by jamescro** [comment]
I just ran this successfully on the same emulator. Could you check the Configuration Manager to make sure that the Build and Deploy steps are checked for the Android project? I'll see if I can find someone who can reproduce this.

**Comment by jamescro** [comment]
I've tried this from a fresh clone and can set break points and debug as expected. Tomorrow I will find someone to install all of the tools and the sample on a clean machine and see if we can reproduce there.

**Comment by jamescro** [comment]
I was never able to reproduce this. Closing for now. Please reopen if you're still seeing it.
