### ISSUE TITLE
Msal with AD + ACS registered users

### ISSUE THREAD

**Issue by geralexgr** [microsoftgraph/xamarin-csharp-connect-sample#4]
Can you post an example for AcquireTokenSilentAsync but with ACS settings ? Can i authenticate registered users with acs + ad + msal ?

**Comment by jamescro** [comment]
Unfortunately MSAL does not support ACS.

**Comment by geralexgr** [comment]
@jamescro Do  you maybe know another method for authenticating users with ad + acs in xamarin forms ?

**Comment by jamescro** [comment]
Again, unfortunately this isn't a scenario that we're actively supporting. Why precisely are you using ACS?

**Comment by geralexgr** [comment]
I have also posted in [azure forums](https://social.msdn.microsoft.com/Forums/azure/en-US/4fc9841e-3d3a-4052-94e0-78d2604ac3fd/azure-active-directory-acs-authentication)
That is the way a company has its registered users, and i need to get the token for them.
Previously in adal for xamarin forms , acs was supported. Will  authentication for acs be implemented in the future for msal, or will be not supported at all ?
